### ISSUE TITLE
PAAS how to handle overlapping roles across companies

### ISSUE THREAD

**Issue by patagoniahiker** [mfidemraizer/stackredis.aspnet.identity#2]
Hello, as this article describes, how can I allow organizations/companies name their own roles, and keep them under the scope of their umbrella.

http://stackoverflow.com/questions/32601679/can-asp-identity-handle-multitenancy-i-have-collisions-in-role-names-in-asp-ide

HomeDepot : Managers Users
CocaCola:    : Mangers Uaers

**Comment by mfidemraizer** [comment]
But is this an issue with this ASP.NET Identity implementation to Redis, or are you looking for a generic solution to your issue?

**Comment by patagoniahiker** [comment]
I am looking for generic solution. I am trying your solution on Redis and was trying to adopt it.  :+1: 

I was thinking Nested Roles, so in fact HomeDepot would be a role, which would then contain/nest _Managers, Users, Editors_

**Comment by mfidemraizer** [comment]
@patagoniahiker  I'll take a look on the next days, I'm very very very (x1000) busy until next weekend. 

BTW I feel that this should be a limitation of how ASP.NET Identity is architected, but anyway, it'll be useful trying think how can we workaround the whole limitation ;)

**Comment by patagoniahiker** [comment]
I agree on the limitation till a certain part. However, if you're a provider (not quite SAAS), where you have a few clients who are your customers, and these customers happen to be organizations (4 to 10 nested users) rather than individuals this falls short of addressing that scenario. I was asking for your help with that :+1:

**Comment by patagoniahiker** [comment]
Hi any update :)

**Comment by mfidemraizer** [comment]
Do you still need this?
